name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: hy0tic/common-runner-image
    steps:
    - uses: actions/checkout@v3
    - run: | 
        op upload
    
