name: Upload to Dev S3

on:
    push:
        branches: [vcs-issue]
    pull_request:
        branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: hy0tic/common-runner-image
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1' # specify your region

    - run: | 
        cd repo
        op hello
    
