name: PR Checks

on:
    push:
        branches: [vcs-issue]
    pull_request:
        branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: hy0tic/common-runner-image
    steps:
    - uses: actions/checkout@v4
    - run: | 
        go build 
    
