name: Upload to Prod S3

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: hy0tic/common-runner-image
    steps:
    - run: |
        git clone --depth=1 https://github.com/${{ github.repository }} repo
        cd repo
        git checkout ${{ github.ref_name }}
        ls -lah

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1' # specify your region

    - run: | 
        cd repo
        op uploaddev
    
